import Image from "next/image";
import Link from "next/link";
import { SocialSubmitButton } from "@/components/social/submit-button";
import { sendNudgeAction, toggleFollowAction, toggleLikeAction } from "@/lib/actions/social";
import { getSocialPage } from "@/lib/queries/social";

export default async function FeedPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q } = await searchParams;
  const { feed, users, searchError } = await getSocialPage(q);
  const base = process.env.NEXT_PUBLIC_SUPABASE_URL;
  return <main><div className="flex items-center justify-between"><h1 className="text-2xl font-bold">关注动态</h1><Link href="/notifications" className="min-h-11 rounded-xl bg-white px-4 py-3 text-sm font-semibold">通知</Link></div>
    <form method="get" className="mt-5 flex gap-2"><label className="sr-only" htmlFor="user-search">搜索用户</label><input id="user-search" name="q" defaultValue={q} placeholder="搜索 username 或昵称" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-4 py-3"/><button className="min-h-11 rounded-xl bg-slate-900 px-4 font-bold text-white">搜索</button></form>
    {searchError && <p className="mt-2 text-sm text-rose-600">{searchError}</p>}
    {q && <section className="mt-4 space-y-2">{users.length === 0 && !searchError ? <p className="rounded-2xl bg-white p-4 text-sm text-slate-500">没有找到用户</p> : users.map(user => <article key={user.id} className="flex items-center gap-3 rounded-2xl bg-white p-3">{user.avatar_path ? <Image unoptimized src={`${base}/storage/v1/object/public/avatars/${user.avatar_path}`} alt="" width={44} height={44} className="size-11 rounded-full object-cover"/> : <div className="flex size-11 items-center justify-center rounded-full bg-emerald-100">🌱</div>}<Link href={`/u/${user.username}`} className="min-w-0 flex-1"><p className="truncate font-bold">{user.display_name}</p><p className="truncate text-xs text-slate-500">@{user.username}</p></Link><form action={toggleFollowAction}><input type="hidden" name="targetId" value={user.id}/><SocialSubmitButton className="min-h-11 rounded-xl border border-emerald-500 px-3 text-sm font-bold text-emerald-600">{user.is_following ? "取消关注" : "关注"}</SocialSubmitButton></form></article>)}</section>}
    <h2 className="mb-3 mt-7 text-lg font-bold">最近打卡</h2>{feed.length === 0 ? <section className="rounded-3xl bg-white p-6 text-center"><p className="font-bold">还没有关注动态</p><p className="mt-2 text-sm text-slate-500">搜索用户并关注后，这里会显示他们最近的打卡。</p></section> : <section className="space-y-3">{feed.map(item => <article key={`${item.user_id}-${item.checkin_date}`} className="rounded-3xl bg-white p-5"><div className="flex items-center justify-between"><Link href={`/u/${item.username}`}><p className="font-bold">{item.display_name}</p><p className="text-xs text-slate-500">@{item.username}</p></Link><time className="text-xs text-slate-400">{item.checkin_date}</time></div><p className="mt-4">今天完成运动 🔥</p><p className="mt-1 text-sm text-slate-500">累计打卡 {item.total_checkin_days} 天</p><div className="mt-4 flex gap-2"><form action={toggleLikeAction}><input type="hidden" name="checkinId" value={item.checkin_id}/><SocialSubmitButton className={`min-h-11 rounded-xl px-4 text-sm font-bold ${item.liked_by_me ? "bg-rose-50 text-rose-600" : "bg-slate-100 text-slate-600"}`}>❤️ {item.like_count}</SocialSubmitButton></form>{item.can_nudge && <form action={sendNudgeAction}><input type="hidden" name="targetId" value={item.user_id}/><SocialSubmitButton className="min-h-11 rounded-xl bg-amber-50 px-4 text-sm font-bold text-amber-700">🔥 催TA运动</SocialSubmitButton></form>}</div></article>)}</section>}
  </main>;
}
